parameters:
    sirian.sphinx.connection.class: Sirian\SphinxBundle\SphinxQL\Connection
    sirian.sphinx.manager.class: Sirian\SphinxBundle\Manager
    sirian.sphinx.query_logger.class: Sirian\SphinxBundle\Logger\QueryLogger
    sirian.sphinx.data_collector.class: Sirian\SphinxBundle\Profiler\SphinxDataCollector

services:
    sirian.sphinx.manager:
        class: %sirian.sphinx.manager.class%
        arguments:
            - %sirian.sphinx.connections%
            - %sirian.sphinx.default_connection%
        calls:
            - ['setContainer', [@service_container]]

    sirian.sphinx.query_logger:
        class: %sirian.sphinx.query_logger.class%
        arguments: [@?logger, @?debug.stopwatch]

    sirian.sphinx.connection:
        class: %sirian.sphinx.connection.class%
        abstract: true
        calls:
            - [setQueryLogger, [@sirian.sphinx.query_logger]]

    sirian.sphinx.data_collector:
        class: %sirian.sphinx.data_collector.class%
        arguments: [@sirian.sphinx.query_logger]
        tags:
            - { name: data_collector, template: 'SirianSphinxBundle:Profiler:collector.html.twig', id: sphinx}
